### ISSUE TITLE
Change landing so that it reflects modern situation

### ISSUE THREAD

**Issue by backmeupplz** [ArbeitBot/ArbeitBot#4]
Due to the recent events (open-sourcing the bot and reaching >1000 users), we need to change our landing page (arbeitbot.com) to act more professional yet providing people with more relevant information. General suggestions from users' and industry specialists' feedback:
1. Move away from the concept of `Telegram bot freelance market` towards the concept of `Open-source freelance market` that should decrease bounce rate of people who came to ArbeitBot landing page but didn't want to install the bot as it exists within Telegram
2. Better illustrate the concepts of why our freelance market is different from other freelance markets and the value this concept brings to users
3. Emphasise that bot is cross-platform (web, ios, android, wp, etc.) because it's based on Telegram. Maybe substitute screenshots of iphone with screenshots of the most popular platforms, including web, ios, android
4. Better space usage (no "empty" blocks)
5. Illustrate roadmap of what we are going to do next (i.e. new freelancers rating algorithm, facebook messenger version, slack version) with links to relevant github issues

**Comment by backmeupplz** [comment]
Started a mockup file for the new landing here: https://github.com/ArbeitBot/ArbeitBot-landing/blob/gh-pages/NEWSITE.md

**Comment by Akiyamka** [comment]
A great landing page! Perhaps it is the stat would be even better if you change the font of the logo (Сopperplate Font) to a more modern?
